# Generated by Django 4.2.3 on 2023-07-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_author_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='boards.board', verbose_name='게시물'),
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='boards.user', verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='boards.user', verbose_name='아이디'),
        ),
    ]
