# Generated by Django 4.2.3 on 2023-07-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comment_board_alter_board_author_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
